### PR TITLE
Migrate Android project to use AndroidX support libraries

### PR DESCRIPTION
**Pull request by aarongrider**
- Simplify project root build.gradle file to match Android convention
- Migrate to build tools 28
- Use AndroidX support libraries

### CODE REVIEW

**Comment by osdnk** [comment]
Thanks for 4th PR according to this issue
#410 
#460 
#524

Can someone figure why Travis cannot pass with these changes?

**Comment by osdnk** [comment]
```
* What went wrong:
Could not resolve all files for configuration ':@react-native-community_slider:debugCompileClasspath'.
> Could not find com.android.support:appcompat-v7:28.0.3.
```

**Comment by aarongrider** [comment]
We've got a little catch 22 going on here: The E2E and Example Android projects will not build using AndroidX because they require dependencies that haven't yet been updated (react-native-community_slider), but if they are not AndroidX projects, they cannot consume react-native-gesture-handler (which I believe is the issue the other PRs are having). I am open to any community feedback or suggestions on this. In the meantime I will try to figure out a solution.

**Comment by osdnk** [comment]
Could you open PR to `react-native-community/slider`? I’ll do my best to have merged it soon. 
Also, is this slider required in E2E app?

**Comment by osdnk** [comment]
Oh, maybe we temporarily want to change android test to build E2E instead of an Example?

**Comment by aarongrider** [comment]
I'm good with that! I see see if I can get E2E running.

**Comment by aarongrider** [comment]
I'm a bit confused as to why E2E isn't currently configured to run on Android but it looks like it would take a bit of work. I think it might be best to try and get the current Android configuration working. I just submitted a PR to react-native-slider. 
https://github.com/react-native-community/react-native-slider/pull/47

We should probably revisit getting E2E running for Android, if E2E tests are designed to be run on that platform?

**Comment by osdnk** [comment]
I didn’t manage to make it workable. I can elaborate on it if you wish, but there were problem with HAXM and I gave up  ¯\_(ツ)_/¯. Now we only check whether example in compilable, which is also kind of important message.

**Comment by aarongrider** [comment]
Great. Working on getting my changes working in react-native-slider. I will update this PR when those changes are merged.

**Comment by osdnk** [comment]
Could you reopen? I don’t want to have it lost. Also, I think that process of merging and releasing changes to slider won’t take long

**Pull request closed without merging**
