### PR TITLE
Type Swipeable module the right way

### PR DESCRIPTION
**Pull request by henrikra**
When you import `Swipeable` like this `import Swipeable from 'react-native-gesture-handler/Swipeable';` it will get right types now from TypeScript. Before this PR TS compiler errored.

⚠️  Please review this PR with query param `w=1` (or [press here](https://github.com/kmagiera/react-native-gesture-handler/pull/256/files?w=1)) so it ignore white space changes. Otherwise this PR looks too big ;)

### CODE REVIEW

**Comment by osdnk** [comment]
@krzysztofciombor, would you mind reviewing it?

**Comment by henrikra** [comment]
@kmagiera I have fixed the merge conflict

**Comment by kmagiera** [comment]
Thanks @henrikra ! Appreciate your help a lot with all your typescript fixes and other PR!

**Comment by henrikra** [comment]
No worries!

**Comment by henrikra** [comment]
Btw can you do new release :D

**Comment by kmagiera** [comment]
Just published 1.0.7, cheers!

**Pull request merged**
