### PR TITLE
Pass navigatorButtons static component so it can be accessed by ...

### PR DESCRIPTION
**Pull request by joserocha3**
navigation library

### CODE REVIEW

**Comment by joserocha3** [comment]
This change allows for the functionality found [here](https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator). Without it, buttons declared within the component class using `static navigatorButtons:  {...}` do not show up.

**Comment by kmagiera** [comment]
Thanks for working on this @joserocha3 

I think it would be better to use a more generic solution as there are perhaps some other static fields that deserve to be copied. I recommend that we use this instead: https://github.com/mridgway/hoist-non-react-statics

Would you be open to updating your pull request with my suggestion?

**Comment by joserocha3** [comment]
Great idea @kmagiera. I have updated it.

**Comment by kmagiera** [comment]
Sweet! Thanks a ton @joserocha3 Will push it out to NPM with the next alpha release

**Pull request merged**
