### PR TITLE
Migrate to AndroidX

### LINKED ISSUE #394: Project won't compile when androidx and jetifier are enabled (SDK build tools >28.0.0)
As of version 28.0.0 of the Android SDK build tools the support library is being phased out in favour of Androidx. Jetifier attempts to bridge this gap by converting external packages to use Androidx.

When both Androidx and Jetifier are enabled in a project's `gradle.properties` (see below), jetifier (presumably) prevents the support library from being included in the project locally, and therefor into `node_modules`

```gradle.properties
# gradle.properties
android.useAndroidX=true
android.enableJetifier=true
```

The result is an error preventing compilation:

```
node_modules/react-native-gesture-handler/[...]/RNGestureHandlerEvent.java:3: error: package android.support.v4.util does not exist
import android.support.v4.util.Pools;
                              ^
```

This can be fixed by upgrading to androidx. Replacing the offending line (and anywhere else Pools is being imported) with `import androidx.core.util.Pools;` would do the trick.

Of course that would cause people who are not on 28.x.x headaches. And this isn't a problem if you aren't using Jetifier (I can get it to compile past the error by turning it off, but am then faced with having to downgrade as whole).

### PR DESCRIPTION
**Pull request by hyochan**
Closes #394 #649

This `PR` is related #410 however, this somehow not worked well (build failed).
I've managed to test this successfully.

### CODE REVIEW

**Comment by chenop** [comment]
any update on this merge?

**Comment by hyochan** [comment]
@chenop You can checkout #656 for improvement

**Comment by chenop** [comment]
Thanks @hyochan - just to save others few minutes - it means do the following:
`npm i https://github.com/hyochan/react-native-gesture-handler.git#package-names`

**Comment by kmagiera** [comment]
Appears there are some CI failures related to thie PR, do you mind taking a look?

**Comment by alessandro-bottamedi** [comment]
Hi, it seems that this is the "AndroidX" pull that will be merged, right?

**Comment by hyochan** [comment]
@alessandro-bottamedi Yes. However, I prefer you to use #656 which is an enhancement. @kmagiera Thank you for approving this `PR`. However, I'd like you to look at #656 which is an improvement. I've added description of why updates are necessary.

**Comment by hyochan** [comment]
@se-bastiaan Thanks for the detailed review. I'll follow up your comment in #656

**Pull request closed without merging**
