### PR TITLE
Remove ViewPager and Slider in favor of exporting createNativeWrapper

### LINKED ISSUE #482: ViewPagerAndroid and Slider moved from RN 0.59 to external packages
Warning: ViewPagerAndroid has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/viewpager' instead of 'react-native'. See https://github.com/react-native-community/react-native-viewpager

Warning: Slider has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/slider' instead of 'react-native'. See https://github.com/react-native-community/react-native-slider

### PR DESCRIPTION
**Pull request by karanjthakkar**
Fixes #482 

In RN 0.59 `ViewPager` and `Slider` are going to be dropped and therefore they call for being dropped from RNGH core. However, since there're use cases of these components, decided not to drop support for them at all, but to expose function for creating generic components with pure native ones.

### CODE REVIEW

**Comment by osdnk** [comment]
Hello, @karanjthakkar 
I'm not into adding this dependencies. How about exporting function for creating components?

**Comment by karanjthakkar** [comment]
@osdnk Do you mean removing ViewPagerAndroid and Slider support from RNGH and allowing consumers to wrap them on their own?

**Comment by osdnk** [comment]
Yes, I don't think if it's good to add peers if we actually do not require them (I know it's done already but I see no good reason to add it here as well)

**Comment by karanjthakkar** [comment]
That's fine. So if I understand correctly:

1. instead of using the third party packages, you want to remove Slider and ViewPagerAndroid from the codebase
2. and we want to let consumers create their own wrappers by exposing `createNativeWrapper` externally

Is that right?

**Comment by osdnk** [comment]
yes. I know it's a breaking change, but I'm afraid that it's not big deal since it's the only issue related and it's not very popular. 
I'll include it in release notes.

**Comment by karanjthakkar** [comment]
Sounds good. Would you like me to do the necessary changes in this PR?

**Comment by osdnk** [comment]
I could do it as well. However, it's your honour to be so reactive and thanks to you we will manage to prevent users' crashes in the nearest future! 😃

**Comment by osdnk** [comment]
@karanjthakkar 
Could you add some docs for this illustrating how to it with these examples (ViewPager and Slider)?

**Comment by karanjthakkar** [comment]
1. Where do you think would be the right place to add docs for `createNativeWrapper`? 
2. There is still some usage of `ViewPagerAndroid` and `Slider` in the `Examples`. How do you recommend I remove it? Or do you want to keep it there?

**Comment by osdnk** [comment]
1. I think that `docs/handlers.md` is right place (under list of exported components)
2. I'd like to keep them alive. It would be very nice example of using this wrapper.

**Comment by karanjthakkar** [comment]
> I think that docs/handlers.md is right place (under list of exported components)

I'll check it out.

> I'd like to keep them alive. It would be very nice example of using this wrapper.

That would mean I need to add the third party packages in the Examples project right? And then use createNativeWrapper to create the wrapped version of it and use that in place of the original one?

**Comment by osdnk** [comment]
Yup

**Comment by osdnk** [comment]
Ooops, sorry

**Comment by karanjthakkar** [comment]
No problem. Thanks for the tips. I'll take a look soon.

**Comment by osdnk** [comment]
Is it ready, @karanjthakkar?
May I merge?

**Comment by karanjthakkar** [comment]
I'll ping once I have tested the Examples that I changed. Give me some time :)

**Comment by karanjthakkar** [comment]
@osdnk I've verified that the examples work as expected. Feel free to merge once the CI is green. Thanks for helping me out 🙂

**Comment by ujwal-setlur** [comment]
Any idea when a new release with this change will be pushed out?

**Pull request merged**
