### PR TITLE
update android support library to androidx

### PR DESCRIPTION
**Pull request by OmranElmasry**

### CODE REVIEW

**Comment by rszalski** [comment]
Shouldn't this also enable AndroidX and jetifier in the `gradle.properties`? There are already PRs at various stages of completion for AndroidX Migration:

• https://github.com/kmagiera/react-native-gesture-handler/pull/650
• https://github.com/kmagiera/react-native-gesture-handler/pull/524
• https://github.com/kmagiera/react-native-gesture-handler/pull/460

Maybe we can consolidate them?

**Comment by kmagiera** [comment]
Thank you @OmranElmasry for sending this. Would love to finally merge one of the androidX migration PRs, however there is not a single one passing CI checks. Would you mind taking a look? I think it'd require that you migrate example project

**Comment by sibelius** [comment]
image

**Comment by OmranElmasry** [comment]
in gradle.properties

```
android.useAndroidX=true
android.enableJetifier=true

```

**Comment by jdnichollsc** [comment]
Hey guys, check this tweet for **AndroidX** support with backward compatibility 👍 https://twitter.com/jdnichollsc/status/1162451046544879616

**Comment by osdnk** [comment]
It's already done. Thank you!

**Pull request closed without merging**
